my_blog/main/urls.py
from django.urls import path
from .views import home, about, contact

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact')
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', include('main.urls')),
    path('', include('register.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/posts/urls.py
from django.urls import path
from .views import posts_list, posts_details

app_name = 'posts'

urlpatterns = [
    path('', posts_list, name='list'),
    path('<int:post_id>', posts_details, name='details')
]

my_blog/register/urls.py
from django.urls import path
from .views import register_request, login_request, logout_request

app_name = "register"
urlpatterns = [
    path('register/', register_request, name="register"),
    path('login/', login_request, name="login"),
    path('logout/', logout_request, name= "logout")
]

my_blog/tags/urls.py
from django.urls import path

my_blog/main/models.py
from django.db import models
#from django.utils.timezone import timedelta, now


class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    bio = models.TextField(max_length=2000)


class Timestamped(models.Model):
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

my_blog/posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts'
                               )
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('tags.Tag', related_name='posts')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return f'{self.id} {self.title}'

my_blog/register/models.py
from django.db import models

# Create your models here.

my_blog/tags/models.py
from django.db import models
from django.utils.text import slugify


class Tag(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return f"{self.name}"

my_blog/main/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField()
    name = forms.CharField(widget=forms.TextInput())
    content = forms.CharField(widget=forms.Textarea)

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = 'contact'
        self.helper.layout = Layout(
            Fieldset(
                'Dodaj post',
                'email',
                'naem',
                'content'
            ),
            ButtonHolder(
                Submit('submit', 'Dodaj', css_class='btn btn-primary'),
                css_class="d-flex justify-content-end"
            )
        )

my_blog/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

my_blog/tags/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from django import forms
from .models import Tag


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name', 'slug']
        labels = {
            'name': 'Name',
            'slug': 'Slug'
        }

    def __int__(self, *args, **kwargs):
        super().__int__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = 'contact'
        self.helper.layout = Layout(
            Fieldset(

            )
            ,
            ButtonHolder(
                Submit('submit', 'Add', css_class='btn btn-primary'),
                css_class="d-flex justify-content-end"
            )
        )

my_blog/main/views.py
from django.shortcuts import render
from .forms import ContactForm


def home(request):
    return render(request,'main/main.html')


def about(request):
    return render(request, 'main/about.html')


def contact(request):
    form = ContactForm()
    return render(request, 'main/contact.html', {'form': form})

my_blog/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Post
from tags.models import Tag
from django.core.paginator import Paginator

def posts_list(request):
    posts_list = Post.objects.all()
    tags_list = Tag.objects.all()
    q = request.GET.get("title")
    tag = request.GET.get("tags")
    if title:
        posts_list = posts_list.filter(title__icontains=title)
    elif tag:
        posts_list = posts_list.filter(tags__name__icontains=tag)

    paginator = Paginator(posts_list, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'posts_list': page_obj, 'tags_list': tags_list}
    return render(request, 'posts/list.html', context)


def posts_details(request, post_id: int):
    post_details = Post.objects.get(pk=post_id)
    context = {'details': post_details}
    return render(request, 'posts/details.html', context)

my_blog/register/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:homepage")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="accounts/register.html", context={"register_form":form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:home")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="accounts/login.html", context={"login_form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect("main:home")

my_blog/main/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/6c33ff7834.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link href="{% static 'main/sass/css/style.css' %}" rel="stylesheet">
    {% block style %} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="header-img">
            <div class="header-text">
                <h1>The Uncle Moris Blog.</h1>
                <p></p>
            </div>
            <div class="header-bg"></div>
        </div>
    </header>
        <nav>
            <ul class="nav-bar">
            <li class="nav-item">
                <a href="{% url 'main:home' %}"> Home </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'posts:list' %}"> Posts </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'main:contact' %}"> Contact </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'register:logout' %}">Logout</a>
            </li>
            {% else  %}
             <li class="nav-item">
                <a href="{% url 'register:login' %}">Login</a>
            </li>

            <li class="nav-item">
                <a href="{% url 'register:register' %}">Register</a>
            </li>
            {% endif %}
            </ul>
        </nav>
    <main class="content">
        {% block content %}
        {% endblock %}
    </main>



<!-- New Footer -->
    <div class="container">
  <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">


    <div class="col mb-3">

    </div>

    <div class="col mb-3">
      <h5>Contact</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="{% url 'main:contact' %}" class="nav-link p-0 text-muted">Home</a></li>

      </ul>
    </div>

    <div class="col mb-3">
      <h5>my media</h5>
      <ul class="nav flex-column">
          <li><a href="https://www.linkedin.com/in/maurycy-wo%C5%BAnica" target="_blank"><i class="fa-brands fa-linkedin"></i></a></li>
          <li><a href="https://github.com/Uncle-Moris" target="_blank"><i class="fa-brands fa-github"></i></a></li>
          <li><a href="https://www.youtube.com/channel/UCkjLEx2izZMNuCD25dVVWwg" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
          <li><a href="https://www.instagram.com/unclemoris/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
          <li><a href="https://twitter.com/moris_uncle" target="_blank"><i class="fa-brands fa-twitter"></i></a></li>
      </ul>
    </div>
    <div class="col mb-3">
      <p class="text-muted">© 2022</p>
    </div>
  </footer>
<!-- end of New Footer -->
</div>

    <script src="{% static 'main/js/main.js' %}"></script>

</body>
</html>

my_blog/main/templates/main/about.html
{% extends 'home.html' %}
{% load static %}
{% load thumbnail %}

<!-- The static title of About template  -->
{% block title %}
    <h1 class="page-title">The Title of About Template</h1>
{% endblock %}


{% block content %}
<div>
   <h1>To Ja Maurycy</h1>

    <div class="square">
        Square
    </div>
    <button class="sq-btn">btn</button>

   <p>
      I'm Maurycy !!!
      <br>
      I love creating new projects.
   </p>
</div>
{% endblock %}

my_blog/main/templates/main/contact.html
{% extends 'home.html' %}

{% block title %} Contact {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<form action="post" class="my-form">
{% crispy form %}
</form>
{% endblock %}

my_blog/main/templates/main/main.html
{% extends 'home.html' %}
{% load static %}
{% load thumbnail %}
<!-- The static title of current template  -->
{% block title %}
    Umm lemony
{% endblock %}

{% block content %}

    {% thumbnail 'main/img/janpawel.jpeg' "200x200" as img %}


    <!--<img src="{% static 'main/img/janpawel.jpeg' %}" id="beautiful_me" class="pope"> -->

    <img src="{{ img.url }}" class="pope">
    {% endthumbnail %}
    <button class="alert-btn">Alert button</button>
{% endblock %}

my_blog/posts/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/6c33ff7834.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header> Sample header</header>
    <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li class="nav-item">
                <a href="{% url 'posts:list' %}" class="nav-link px-2 link-secondary"> All Posts </a>
            </li>
            <li>
                <a href="{% url 'main:home' %}" class="nav-link px-2 link-secondary"> Home </a>
            </li>
            <li>
                <a href="{% url 'main:contact' %}" class="nav-link px-2 link-secondary"> Home </a>
            </li>
        </ul>
        </ul>
    </nav>
    <main class="container justify-content-center">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="bg-blue text-center text-white">
        <div class="my-media">
            <strong>My media</strong>
            <ul>
                 <li><a href="https://www.linkedin.com/in/maurycy-wo%C5%BAnica" target="_blank"><i class="fa-brands fa-linkedin"></i></a></li>
                 <li><a href="https://github.com/Uncle-Moris" target="_blank"><i class="fa-brands fa-github"></i></a></li>
                 <li><a href="https://www.youtube.com/channel/UCkjLEx2izZMNuCD25dVVWwg" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
                 <li><a href="https://www.instagram.com/unclemoris/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
                 <li><a href="https://twitter.com/moris_uncle" target="_blank"><i class="fa-brands fa-twitter"></i></a></li>
            </ul>
        </div>
        <div>
            <p>Read more about me <a href="{% url 'main:about' %}">here</a></p>
        </div>
        <div>
            Contact
        </div>
    </footer>
</body>
</html>

my_blog/posts/templates/posts/details.html
{% extends 'home.html' %}
<!-- The static title of Post  -->
{% block title %}
{{ details.title }}
{% endblock %}
{% block content %}
<section class="post_content container">
    <h1 class="page-title">{{ details.title }}</h1>
    <p >
        {{ details.content }}
    </p>
</section>
{% endblock %}

my_blog/posts/templates/posts/list.html
{% extends 'home.html' %}

<!-- Static -->
{% load static %}
<!-- Style -->
{% block style %}<link href="{% static 'posts/css/style.css' %}" rel="stylesheet" >{% endblock %}

<!-- The title of post list   -->
{% block title %} The Posts {% endblock %}

{% block content %}

    <h1>The Posts</h1>
    <form class="posts_search_bar">
            <input type="text"  id="title" name="title">
            <label for="tags"></label>
            <select id="tags" name="tags">
                    <option value="">wybierz</option>
                {% for tag in tags_list %}
                    <option value="{{tag.name}}">{{ tag.name }} </option>
                {% endfor %}
            </select>
        <input type="submit" value="search">
    </form>
    <ul class="posts_list container">
        {% for post in posts_list %}
        <li >
            <a class="link-to-post" href="{% url 'posts:details' post.id %}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>

{% endblock %}

my_blog/posts/templates/posts/posts_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Posts list</h1>
    <ol>
        {% for post in posts_list %}
        <li>{{ post.title}}   {{post.content}}</li>
        {% endfor %}
    </ol>


</body>
</html>

my_blog/register/templates/accounts/login.html
{% extends "home.html" %}

{% block title%}Login page{% endblock %}
{% block content %}

{% load crispy_forms_tags %}
<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register/">Create an account</a>.</p>
</div>

{% endblock %}

my_blog/register/templates/accounts/register.html
{% extends "home.html" %}

{% block title%} Create an Account {% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login/">login</a> instead.</p>
</div>

{% endblock %}